language: python
sudo: false
dist: trusty
services:
- docker
cache:
  directories:
  - "$HOME/.cache/pip"
_install: &_install
  - pip install --upgrade pip
  - pip install -r requirements.txt --no-binary wmd codecov
  - pip install -e .
_coverage: &_coverage
  - SCRIPT="coverage run -m unittest discover"
matrix:
  include:
    - python: 3.4
      env: *_coverage
      before_install: *_before_install
      install: *_install
    - python: 3.5
      env: *_coverage
      before_install: *_before_install
      install: *_install
    - python: 3.6
      env: SCRIPT="pep8 --max-line-length=99 ."
      install: pip install pep8
    - python: 3.6
      env: *_coverage
      before_install: *_before_install
      install: *_install
      after_success:
        - codecov
  fast_finish: true
before_script:
- BBLFSH_DRIVER_IMAGES="python=docker://bblfsh/python-driver:v0.8.2;java=docker://bblfsh/java-driver:v0.6.0" docker run -e BBLFSH_DRIVER_IMAGES -d --privileged -p 9432:9432 --name bblfsh bblfsh/server:v0.7.0
script:
- (eval "$SCRIPT")
notifications:
  email: false
